[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate resolve --applied 20260523061955_tambah_kendaraan_dan_rental && npm run db:deploy && npm run start:prod"